package com.youcruit.billogram.objects.response.event;

import com.google.gson.annotations.SerializedName;

public enum BillogramEvent {
    @SerializedName("BillogramCreated") BILLOGRAM_CREATED,
    @SerializedName("BillogramSent") BILLOGRAM_SENT,
    @SerializedName("Payment") PAYMENT,
    @SerializedName("ReminderSent") REMINDER_SENT,
    @SerializedName("Overdue") OVERDUE,
    @SerializedName("Credit") CREDIT,
    @SerializedName("BillogramEnded") BILLOGRAM_ENDED,
    @SerializedName("Resent") RESENT,
    @SerializedName("DeliveryAccepted") DELIVERY_ACCEPTED,
    @SerializedName("DeliveryFailed") DELIVERY_FAILED,
    @SerializedName("EmailNotAccepted") EMAIL_NOT_ACCEPTED,
    @SerializedName("LetterSent") LETTER_SENT,
    @SerializedName("OverpaymentAdjustment") OVERPAYMENT_ADJUSTMENT,
    @SerializedName("InterestStarted") INTEREST_STARTED,
    @SerializedName("CustomerMessage") CUSTOMER_MESSAGE,
    @SerializedName("CreditorMessage") CREDITOR_MESSAGE,
    @SerializedName("DataChange") DATA_CHANGE,
    @SerializedName("InvoiceSent") INVOICE_SENT,
    @SerializedName("Collection") COLLECTION,
    @SerializedName("CollectorPayment") COLLECTOR_PAYMENT,
    @SerializedName("CollectionEnded") COLLECTION_ENDED,
    @SerializedName("CollectionCancelled") COLLECTION_CANCELLED,
    @SerializedName("CollectionStatusUpdate") COLLECTION_STATUS_UPDATE,
    @SerializedName("FactoringRequest") FACTORING_REQUEST,
    @SerializedName("BillogramSold") BILLOGRAM_SOLD,
    @SerializedName("FactoringCreditRequest") FACTORING_CREDIT_REQUEST,
    @SerializedName("FactoringDenied") FACTORING_DENIED,
    @SerializedName("FactoringCreditRequestDenied") FACTORING_CREDIT_REQUEST_DENIED,
    @SerializedName("Writeoff") WRITEOFF,
    @SerializedName("NewInvoicePDF") NEW_INVOICE_PDF,
    @SerializedName("Deleted") DELETED,
    @SerializedName("PaymentScheduled") PAYMENT_SCHEDULED,
    @SerializedName("PaymentFailed") PAYMENT_FAILED,
    @SerializedName("PaymentSystemCancelled") PAYMENT_SYSTEM_CANCELLED,
    @SerializedName("PaymentSystemUpdated") PAYMENT_SYSTEM_UPDATED,
    @SerializedName("PaymentUserCancelled") PAYMENT_USER_CANCELLED,
    @SerializedName("PaymentUserUpdated") PAYMENT_USER_UPDATED,
    @SerializedName("RecurringPaymentEnabled") RECURRING_PAYMENT_ENABLED,
    @SerializedName("RecurringPaymentDisabled") RECURRING_PAYMENT_DISABLED,
    @SerializedName("RecurringPaymentUpdated") RECURRING_PAYMENT_UPDATED,
    @SerializedName("DeliverySmsFailed") DELIVERY_SMS_FAILED,
    @SerializedName("SmsNotAccepted") SMS_NOT_ACCEPTED,
    @SerializedName("OverpaymentCustomerLiability") OVERPAYMENT_CUSTOMER_LIABILITY,
    @SerializedName("Writedown") WRITEDOWN,
    @SerializedName("RevertWritedown") REVERT_WRITEDOWN,
    @SerializedName("AutogiroFailed") AUTOGIRO_FAILED,
    @SerializedName("EfakturaSent") EFAKTURA_SENT,
    @SerializedName("EfakturaFailed") EFAKTURA_FAILED,
    @SerializedName("SaleAccepted") SALE_ACCEPTED,
    @SerializedName("Respite") RESPITE,
    @SerializedName("RespiteRemoved") RESPITE_REMOVED,

}
